services:
  app:
    image: ${IMAGE_NAME:-ghcr.io/donchong2000/donchong-top}:${IMAGE_TAG:-latest}
    container_name: tailwindui-protocol
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'
